package Pelamar;

import Controller.Manajemen;
import Model.Lamar;
import Model.Pekerjaan;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ade
 */
public class FormRegister extends javax.swing.JFrame {
     Manajemen manajemen;
    /**
     * Creates new form FormRegister
     */
    public FormRegister() throws SQLException {
        initComponents();
        this.manajemen = new Manajemen();
        this.showComboBoxPekerjaan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    public void showComboBoxPekerjaan() throws SQLException {
       
    DefaultComboBoxModel dtm = new DefaultComboBoxModel();
            for (Pekerjaan p : this.manajemen.getDataPekerjaan()) {
                dtm.addElement(p.getSpesialisasi_Pekerjaan());
           }
            
           this.CBPekerjaan.setModel(dtm);
    }
    
   
    
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        JP_Kuning = new javax.swing.JPanel();
        JP_Orange = new javax.swing.JPanel();
        JP_Hitam = new javax.swing.JPanel();
        JL_Nama = new javax.swing.JLabel();
        JL_Alamat = new javax.swing.JLabel();
        JL_TTL = new javax.swing.JLabel();
        JL_Kelamin = new javax.swing.JLabel();
        JL_Agama = new javax.swing.JLabel();
        JL_Pekerjaan = new javax.swing.JLabel();
        JT_Nama = new javax.swing.JTextField();
        JT_Alamat = new javax.swing.JTextField();
        ttl = new javax.swing.JTextField();
        agama = new javax.swing.JTextField();
        JCB_Kelamin = new javax.swing.JComboBox<>();
        JB_Register = new javax.swing.JButton();
        JB_Kembali = new javax.swing.JButton();
        JL_ID = new javax.swing.JLabel();
        JL_Pswd = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        CBPekerjaan = new javax.swing.JComboBox<>();
        JL_identitas = new javax.swing.JLabel();
        JP_Identitas = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Job Applicant Selection System\n");
        setLocation(new java.awt.Point(680, 130));

        JP_Kuning.setBackground(new java.awt.Color(255, 255, 0));

        JP_Orange.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout JP_OrangeLayout = new javax.swing.GroupLayout(JP_Orange);
        JP_Orange.setLayout(JP_OrangeLayout);
        JP_OrangeLayout.setHorizontalGroup(
            JP_OrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );
        JP_OrangeLayout.setVerticalGroup(
            JP_OrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JP_Hitam.setBackground(new java.awt.Color(51, 51, 0));

        JL_Nama.setForeground(new java.awt.Color(255, 255, 255));
        JL_Nama.setText("Nama Lengkap");

        JL_Alamat.setForeground(new java.awt.Color(255, 255, 255));
        JL_Alamat.setText("Alamat");

        JL_TTL.setForeground(new java.awt.Color(255, 255, 255));
        JL_TTL.setText("Tempat / Tgl Lahir");

        JL_Kelamin.setForeground(new java.awt.Color(255, 255, 255));
        JL_Kelamin.setText("Jenis Kelamin");

        JL_Agama.setForeground(new java.awt.Color(255, 255, 255));
        JL_Agama.setText("Agama");

        JL_Pekerjaan.setForeground(new java.awt.Color(255, 255, 255));
        JL_Pekerjaan.setText("Pekerjaan yang dilamar");

        JT_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_NamaActionPerformed(evt);
            }
        });

        JT_Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_AlamatActionPerformed(evt);
            }
        });

        ttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttlActionPerformed(evt);
            }
        });

        agama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agamaActionPerformed(evt);
            }
        });

        JCB_Kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   --- Pilih ---", "Laki - laki", "Perempuan" }));

        JB_Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gtk-save-as.png"))); // NOI18N
        JB_Register.setText("Register");
        JB_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_RegisterActionPerformed(evt);
            }
        });

        JB_Kembali.setText("Kembali");
        JB_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_KembaliActionPerformed(evt);
            }
        });

        JL_ID.setForeground(new java.awt.Color(255, 255, 255));
        JL_ID.setText("ID");

        JL_Pswd.setForeground(new java.awt.Color(255, 255, 255));
        JL_Pswd.setText("Password");

        CBPekerjaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout JP_HitamLayout = new javax.swing.GroupLayout(JP_Hitam);
        JP_Hitam.setLayout(JP_HitamLayout);
        JP_HitamLayout.setHorizontalGroup(
            JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_HitamLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_HitamLayout.createSequentialGroup()
                        .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_Nama)
                            .addComponent(JL_Agama)
                            .addComponent(JL_Kelamin)
                            .addComponent(JL_TTL)
                            .addComponent(JL_Alamat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JT_Nama, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(JT_Alamat)
                            .addComponent(ttl))
                        .addGap(24, 24, 24))
                    .addGroup(JP_HitamLayout.createSequentialGroup()
                        .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_HitamLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(JL_Pekerjaan)
                                .addGap(41, 41, 41)
                                .addComponent(CBPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JP_HitamLayout.createSequentialGroup()
                                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JL_ID)
                                    .addComponent(JL_Pswd))
                                .addGap(84, 84, 84)
                                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agama, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCB_Kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JP_HitamLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(JB_Kembali)
                                .addGap(85, 85, 85)
                                .addComponent(JB_Register)))
                        .addContainerGap(122, Short.MAX_VALUE))))
        );
        JP_HitamLayout.setVerticalGroup(
            JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_HitamLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Nama)
                    .addComponent(JT_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JT_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JP_HitamLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(JL_Alamat)))
                .addGap(33, 33, 33)
                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_TTL))
                .addGap(25, 25, 25)
                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JL_Kelamin)
                    .addComponent(JCB_Kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_HitamLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(JL_Agama))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_HitamLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JP_HitamLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(JL_ID))
                    .addGroup(JP_HitamLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(id)))
                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JP_HitamLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(JL_Pswd))
                    .addGroup(JP_HitamLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pass)))
                .addGap(56, 56, 56)
                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Pekerjaan)
                    .addComponent(CBPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(JP_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Register)
                    .addComponent(JB_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        JL_identitas.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        JL_identitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/003-newspaper.png"))); // NOI18N
        JL_identitas.setText(" IDENTITAS DIRI");

        javax.swing.GroupLayout JP_KuningLayout = new javax.swing.GroupLayout(JP_Kuning);
        JP_Kuning.setLayout(JP_KuningLayout);
        JP_KuningLayout.setHorizontalGroup(
            JP_KuningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_KuningLayout.createSequentialGroup()
                .addComponent(JP_Orange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JP_KuningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_KuningLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(JL_identitas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JP_KuningLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JP_Hitam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        JP_KuningLayout.setVerticalGroup(
            JP_KuningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Orange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_KuningLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JL_identitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(JP_Hitam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout JP_IdentitasLayout = new javax.swing.GroupLayout(JP_Identitas);
        JP_Identitas.setLayout(JP_IdentitasLayout);
        JP_IdentitasLayout.setHorizontalGroup(
            JP_IdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        JP_IdentitasLayout.setVerticalGroup(
            JP_IdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Kuning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JP_Identitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JP_Kuning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JP_Identitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String kelamin;
    private void JT_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_NamaActionPerformed

    private void JB_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_RegisterActionPerformed
//        // TODO add your handling code here:
        kelamin = JCB_Kelamin.getSelectedItem().toString();
        String pekerjaan = CBPekerjaan.getSelectedItem().toString();
        Data.reg.insert(JT_Nama.getText(), JT_Alamat.getText(),agama.getText(),ttl.getText(),kelamin, pekerjaan, id.getText(), pass.getText());
        InformasiPelamar informasiPelamar = new InformasiPelamar(JT_Nama.getText(), JT_Alamat.getText(), ttl.getText(), kelamin, agama.getText(), pekerjaan);
        informasiPelamar.setVisible(false);
   JOptionPane.showMessageDialog(null," Registrasi Berhasil");
    }//GEN-LAST:event_JB_RegisterActionPerformed

    private void JT_AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_AlamatActionPerformed

    private void agamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agamaActionPerformed

    private void JB_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_KembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        new FormPelamar().setVisible(true);
        
    }//GEN-LAST:event_JB_KembaliActionPerformed

    private void ttlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormRegister().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormRegister.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBPekerjaan;
    private javax.swing.JButton JB_Kembali;
    private javax.swing.JButton JB_Register;
    private javax.swing.JComboBox<String> JCB_Kelamin;
    private javax.swing.JLabel JL_Agama;
    private javax.swing.JLabel JL_Alamat;
    private javax.swing.JLabel JL_ID;
    private javax.swing.JLabel JL_Kelamin;
    private javax.swing.JLabel JL_Nama;
    private javax.swing.JLabel JL_Pekerjaan;
    private javax.swing.JLabel JL_Pswd;
    private javax.swing.JLabel JL_TTL;
    private javax.swing.JLabel JL_identitas;
    private javax.swing.JPanel JP_Hitam;
    private javax.swing.JPanel JP_Identitas;
    private javax.swing.JPanel JP_Kuning;
    private javax.swing.JPanel JP_Orange;
    private javax.swing.JTextField JT_Alamat;
    private javax.swing.JTextField JT_Nama;
    private javax.swing.JTextField agama;
    private javax.swing.JTextField id;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField ttl;
    // End of variables declaration//GEN-END:variables
}
