package Job_Aps;

import Admin.Interface;
import Controller.Manajemen;
import Model.Manajemen_Lowongan;
import Model.Pekerjaan;
import Pelamar.FormRegister;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import project_uas.*;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;



public class Job_ApsG extends javax.swing.JFrame {
     Manajemen manajemen;
    private int Idg,Tggl;
    private String Spls;
   
    public Job_ApsG() throws SQLException {
        initComponents();
        this.manajemen = new Manajemen();
        this.showTableGlm();
         this.showComboBoxPk();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
      
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        bggender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LADMIN = new javax.swing.JLabel();
        BKembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LCari = new javax.swing.JLabel();
        TCari = new javax.swing.JTextField();
        LKode = new javax.swing.JLabel();
        LFungsiPkrjn = new javax.swing.JLabel();
        LGaji = new javax.swing.JLabel();
        TKode = new javax.swing.JTextField();
        Ttglg = new javax.swing.JTextField();
        BReset = new javax.swing.JButton();
        BInsert = new javax.swing.JButton();
        LDaftar = new javax.swing.JLabel();
        BHapus = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabelGlm = new javax.swing.JTable();
        CBpk = new javax.swing.JComboBox<>();
        BDt = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TAreaPLM = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane3.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Job Applicant Selection System");
        setBackground(new java.awt.Color(51, 51, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(51, 51, 0));
        setLocation(new java.awt.Point(500, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });

        LADMIN.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LADMIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        LADMIN.setText(" ADMIN");

        BKembali.setText("Kembali");
        BKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKembaliActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        LCari.setForeground(new java.awt.Color(255, 255, 51));
        LCari.setText("Cari ");

        TCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCariActionPerformed(evt);
            }
        });

        LKode.setForeground(new java.awt.Color(255, 255, 51));
        LKode.setText("Id Gelombang");

        LFungsiPkrjn.setForeground(new java.awt.Color(255, 255, 51));
        LFungsiPkrjn.setText("Spesialisasi Pekerjaan");

        LGaji.setForeground(new java.awt.Color(255, 255, 102));
        LGaji.setText("Tanggal");

        TKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKodeActionPerformed(evt);
            }
        });

        Ttglg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtglgActionPerformed(evt);
            }
        });

        BReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancel.png"))); // NOI18N
        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        BInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gtk-save-as.png"))); // NOI18N
        BInsert.setText("Insert");
        BInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BInsertMouseClicked(evt);
            }
        });
        BInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInsertActionPerformed(evt);
            }
        });

        LDaftar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LDaftar.setForeground(new java.awt.Color(255, 255, 102));
        LDaftar.setText("Daftar Lowongan");

        BHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_delete.png"))); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BHapusMouseClicked(evt);
            }
        });
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        TabelGlm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(TabelGlm);

        CBpk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBpk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBpkActionPerformed(evt);
            }
        });

        BDt.setText("Detail");
        BDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LCari)
                .addGap(18, 18, 18)
                .addComponent(TCari, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LKode)
                    .addComponent(LFungsiPkrjn)
                    .addComponent(LGaji))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TKode, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ttglg)
                    .addComponent(CBpk, 0, 195, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LDaftar)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(BInsert)
                                .addGap(69, 69, 69)
                                .addComponent(BReset)
                                .addGap(137, 137, 137))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BHapus)
                        .addGap(81, 81, 81)
                        .addComponent(BDt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LKode, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TKode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LFungsiPkrjn)
                            .addComponent(CBpk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LCari))
                        .addGap(72, 72, 72)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ttglg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LGaji))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BInsert)
                    .addComponent(BReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(LDaftar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BHapus)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BDt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TAreaPLM.setColumns(20);
        TAreaPLM.setRows(5);
        jScrollPane4.setViewportView(TAreaPLM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(LADMIN)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(BKembali)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LADMIN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCariActionPerformed
       
            TCari.addActionListener((KeyEvent)-> {
            DefaultTableModel dataModel = (DefaultTableModel) TabelGlm.getModel();
            String search = TCari.getText();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dataModel);
            TabelGlm.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(search));                
        });
        
        
    }//GEN-LAST:event_TCariActionPerformed

    private void TKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TKodeActionPerformed

    private void BInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInsertActionPerformed
        // TODO add your handling code here:
        
//         
//      
//        Idg = Integer.parseInt(TKode.getText());
//        Spls = CBpk.getSelectedItem().toString();
//        Tggl = Integer.parseInt(Ttglg.getText());
//      
//          
//           Pekerjaan pekerjaan = new Pekerjaan();
//           pekerjaan.setId_Pekerjaan(rs.getInt("ID_PEKERJAAN"));
//           pekerjaan.setSpesialisasi_Pekerjaan(rs.getString("SPESIALISASI_PEKERJAAN"));
//           pekerjaan.setGaji(rs.getInt("Gaji"));
//       
//           Manajemen_Lowongan mjl = new Manajemen_Lowongan();
//        try {
//            mjl.setId_Gelombang(Idg);
//            mjl.setPekerjaan(pekerjaan);
//            mjl.setTanggal(new SimpleDateFormat("dd/MM/yyyy").parse(Tggl.getText()));
//            
//            this.manajemen.insertPkr(pker);
//            this.showTableLowongan();
//            kosong();
//        } catch (SQLException err) {
//            System.out.println(err);
//       } 
        
        
  /*    
      
       Manajemen_Lowongan lwg = new Manajemen_Lowongan();
            Idg = Integer.parseInt(TKode.getText());
            Spls = CBpk.getSelectedItem().toString();
        try {
         //   lwg.setId_Gelombang(Idg);
            lwg.setId_Gelombang(Integer.parseInt(TKode.getText()));
            lwg.getPekerjaan().getSpesialisasi_Pekerjaan();        
            lwg.setTanggal(new Date());
           
            this.manajemen.insertglb(lwg);
            this.showTableGlm();
           // kosong();
        } catch (SQLException err) {
            System.out.println(err);
        } 
      */
      Manajemen_Lowongan mlg = new Manajemen_Lowongan();
                try {
                    mlg.setId_Gelombang(Integer.parseInt(TKode.getText()));
                    mlg.setTanggal(new SimpleDateFormat("dd/MM/yyyy").parse(Ttglg.getText()));
                    mlg.setPekerjaan(manajemen.getDataPekerjaan().get(CBpk.getSelectedIndex()));
                    System.out.println(CBpk.getSelectedIndex());
                    
                    this.manajemen.insertglb(mlg);
                    this.showTableGlm();
                } catch (SQLException | ParseException err) {
                    System.out.println(err);
            
                }
//                
//             
//  
//    Jadwal  = new Jadwal();
//        try {
//            jadwal.setfilm(cinema.getDataFilm().get(pilihfilm.getSelectedIndex()));
//            System.out.println(pilihfilm.getSelectedIndex());
//            jadwal.setKode_Jadwal(Integer.parseInt(kodejadwal.getText()));
//            jadwal.setTgl_Tayang(new SimpleDateFormat("dd/MM/yyyy").parse(tanggal.getText()));
//            jadwal.setWktu_Tayang(waktu.getSelectedItem().toString());
//            jadwal.setRuang(ruangan.getSelectedItem().toString());
//            
//            this.cinema.insertjdwl(jadwal);
//            this.showTableJadwal();
//            kosong();
//        } catch (SQLException | ParseException err) {
//            System.out.println(err);
//        } 
//        
  

  
  
    }//GEN-LAST:event_BInsertActionPerformed

    private void BKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKembaliActionPerformed
        
       dispose();
        try { 
            new Job_Aps().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Job_ApsG.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BKembaliActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
   
            BReset.addActionListener((ActionEvent e) -> {
            TKode.getText();
            CBpk.getSelectedItem();
            Ttglg.getText();
                   
            TKode.setText("");
            CBpk.getSelectedItem().equals("--- Pilih ---");
            Ttglg.setText("");
         
        } );
        
    }//GEN-LAST:event_BResetActionPerformed

    private void TtglgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtglgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TtglgActionPerformed

    private void BInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BInsertMouseClicked


        DefaultTableModel dataModel = (DefaultTableModel) TabelGlm.getModel();
        List list = new ArrayList<>();
        TabelGlm.setAutoCreateColumnsFromModel(true);
        list.add (TKode.getText());
        list.add (CBpk.getSelectedItem());
        list.add (Ttglg.getText());
        dataModel.addRow(list.toArray());     
    
    }//GEN-LAST:event_BInsertMouseClicked

    private void BHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHapusMouseClicked

        DefaultTableModel dataModel = (DefaultTableModel) TabelGlm.getModel();
         int j = TabelGlm.getSelectedRow();
         if (j >= 0) {
             
                 
            dataModel.removeRow(j);
            TKode.getText();
            CBpk.getSelectedItem();
            Ttglg.getText();
            bggender.getSelection();
         }else{ }
                 
    }//GEN-LAST:event_BHapusMouseClicked

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BHapusActionPerformed

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1PropertyChange

    private void CBpkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBpkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBpkActionPerformed

    private void BDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDtActionPerformed
        // TODO add your handling code here:
        
         try {
        Manajemen_Lowongan er = this.manajemen.getDataManajemen_Lowongan().get(this.TabelGlm.getSelectedRow());
        String Teks = ("                               -------- DETAIL LOWONGAN --------" + "\n"
                +"\n"
                + "ID_GELOMBANG                                 : " + er.getId_Gelombang().toString()+"\n"
                + "ID_PEKERJAAN                                 : " + er.getPekerjaan().getId_Pekerjaan().toString()+"\n"
                + "SPESIALISASI PEKERJAAN      : " + er.getPekerjaan().getSpesialisasi_Pekerjaan()+"\n"
                + "GAJI                                         : " + er.getPekerjaan().getGaji().toString()+"\n"
                + "TANGGAL                                      : " + er.getTanggal()+"\n"
                );
        this.TAreaPLM.setText(Teks);
                } catch (SQLException ex) {
                  System.out.println(ex);
                }
    }//GEN-LAST:event_BDtActionPerformed

    
    
    
    public void showComboBoxPk() throws SQLException {
       
    DefaultComboBoxModel dtm = new DefaultComboBoxModel();
            for (Pekerjaan p : this.manajemen.getDataPekerjaan()) {
                dtm.addElement(p.getSpesialisasi_Pekerjaan());
           }
            
           this.CBpk.setModel(dtm);
    }
    
 
    
    
    private void showTableGlm() throws SQLException {
        DefaultTableModel dtmgelom = new DefaultTableModel(new String[]{"Id Gelombang" , "Spesialisasi Pekerjaan" , "Tanggal"}, 0);
        dtmgelom.setRowCount(0);
        
        for (Manajemen_Lowongan ml : this.manajemen.getDataManajemen_Lowongan()) {
            dtmgelom.addRow(new String[]{
                ml.getId_Gelombang().toString(),
                ml.getPekerjaan().getSpesialisasi_Pekerjaan(),
                ml.getTanggal().toString(),
               
            });
           
            
        }
        
            this.TabelGlm.setModel(dtmgelom);
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Job_ApsG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Job_ApsG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Job_ApsG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Job_ApsG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Job_ApsG().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Job_ApsG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDt;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BInsert;
    private javax.swing.JButton BKembali;
    private javax.swing.JButton BReset;
    private javax.swing.JComboBox<String> CBpk;
    private javax.swing.JLabel LADMIN;
    private javax.swing.JLabel LCari;
    private javax.swing.JLabel LDaftar;
    private javax.swing.JLabel LFungsiPkrjn;
    private javax.swing.JLabel LGaji;
    private javax.swing.JLabel LKode;
    private javax.swing.JTextArea TAreaPLM;
    private javax.swing.JTextField TCari;
    private javax.swing.JTextField TKode;
    private javax.swing.JTable TabelGlm;
    private javax.swing.JTextField Ttglg;
    private javax.swing.ButtonGroup bggender;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
