package Job_Aps;

import Admin.Interface;
import Controller.Manajemen;
import Model.Manajemen_Lowongan;
import Model.Pekerjaan;
import Pelamar.FormRegister;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import project_uas.*;



public class Job_Aps extends javax.swing.JFrame {
    Manajemen manajemen;
    private int Idd,Gj;
    private String Spl;
   
    public Job_Aps() throws SQLException {
        initComponents();
        this.manajemen = new Manajemen();
        this.showTableLowongan();
        this.showTableGl();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
      
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        bggender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LADMIN = new javax.swing.JLabel();
        BKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LCari = new javax.swing.JLabel();
        TCari = new javax.swing.JTextField();
        LKode = new javax.swing.JLabel();
        LFungsiPkrjn = new javax.swing.JLabel();
        LGaji = new javax.swing.JLabel();
        TKode = new javax.swing.JTextField();
        TGaji = new javax.swing.JTextField();
        BReset = new javax.swing.JButton();
        BInsert = new javax.swing.JButton();
        LDaftar = new javax.swing.JLabel();
        BHapus = new javax.swing.JButton();
        TPekerjaan = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabelPlm = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabelg = new javax.swing.JTable();
        BDetail = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TAreaPLM = new javax.swing.JTextArea();
        JBSubmit = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane3.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Job Applicant Selection System");
        setBackground(new java.awt.Color(51, 51, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(51, 51, 0));
        setLocation(new java.awt.Point(500, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });

        LADMIN.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LADMIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        LADMIN.setText(" ADMIN");

        BKeluar.setText("Keluar");
        BKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        LCari.setForeground(new java.awt.Color(255, 255, 51));
        LCari.setText("Cari ");

        TCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCariActionPerformed(evt);
            }
        });

        LKode.setForeground(new java.awt.Color(255, 255, 51));
        LKode.setText("Id Pekerjaan");

        LFungsiPkrjn.setForeground(new java.awt.Color(255, 255, 51));
        LFungsiPkrjn.setText("Spesialisasi Pekerjaan");

        LGaji.setForeground(new java.awt.Color(255, 255, 102));
        LGaji.setText("Gaji");

        TKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKodeActionPerformed(evt);
            }
        });

        TGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TGajiActionPerformed(evt);
            }
        });

        BReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancel.png"))); // NOI18N
        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        BInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gtk-save-as.png"))); // NOI18N
        BInsert.setText("Insert");
        BInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BInsertMouseClicked(evt);
            }
        });
        BInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInsertActionPerformed(evt);
            }
        });

        LDaftar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LDaftar.setForeground(new java.awt.Color(255, 255, 102));
        LDaftar.setText("Daftar Lowongan");

        BHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_delete.png"))); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BHapusMouseClicked(evt);
            }
        });
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        TPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPekerjaanActionPerformed(evt);
            }
        });

        TabelPlm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(TabelPlm);

        Tabelg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(Tabelg);

        BDetail.setText("Detail");
        BDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LCari)
                                .addGap(18, 18, 18)
                                .addComponent(TCari, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LKode)
                            .addComponent(LFungsiPkrjn)
                            .addComponent(LGaji)
                            .addComponent(BInsert))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(BReset)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TKode, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TPekerjaan, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TGaji))
                                        .addGap(128, 128, 128))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LDaftar)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BDetail)
                        .addGap(74, 74, 74))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LKode, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TKode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LFungsiPkrjn)
                            .addComponent(TPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LGaji))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BInsert))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LCari))
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LDaftar)
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHapus))
                .addGap(44, 44, 44))
        );

        TAreaPLM.setColumns(20);
        TAreaPLM.setRows(5);
        jScrollPane4.setViewportView(TAreaPLM);

        JBSubmit.setText("Submit");
        JBSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(155, 155, 155)))
                .addGap(471, 471, 471))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(LADMIN)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LADMIN)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(BKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
      private void kosong()
    {
        TKode.setText("");
        TPekerjaan.setText("");
        TGaji.setText("");
    }
    
    
    
    private void TCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCariActionPerformed
       
            TCari.addActionListener((KeyEvent)-> {
            DefaultTableModel dataModel = (DefaultTableModel) TabelPlm.getModel();
            String search = TCari.getText();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dataModel);
            TabelPlm.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(search));                
        });
        
        
    }//GEN-LAST:event_TCariActionPerformed

    private void TKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TKodeActionPerformed

    private void BInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInsertActionPerformed
        // TODO add your handling code here:
        
     
        
        Idd = Integer.parseInt(TKode.getText());
        Spl = TPekerjaan.getText();
        Gj = Integer.parseInt(TGaji.getText());
       
        Pekerjaan pker = new Pekerjaan();
        try {
           pker.setId_Pekerjaan(Idd);
            pker.setSpesialisasi_Pekerjaan(Spl);
            pker.setGaji(Gj);
            
            this.manajemen.insertPkr(pker);
            this.showTableLowongan();
            kosong();
        } catch (SQLException err) {
            System.out.println(err);
       }        
         
    }//GEN-LAST:event_BInsertActionPerformed

    private void BKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluarActionPerformed
        
         int exit=JOptionPane.showConfirmDialog(null,"Yakin Ingin keluar","Keluar",JOptionPane.OK_OPTION );
        if(exit==JOptionPane.OK_OPTION){
            dispose();
             new Interface().setVisible(true);;
        }
        
    }//GEN-LAST:event_BKeluarActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
   
            BReset.addActionListener((ActionEvent e) -> {
            TKode.getText();
            TPekerjaan.getText();
            TGaji.getText();

            TKode.setText("");
            TPekerjaan.setText("");
            TGaji.setText("");

        } );
        
    }//GEN-LAST:event_BResetActionPerformed

    private void TGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TGajiActionPerformed

    private void BInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BInsertMouseClicked


        DefaultTableModel dataModel = (DefaultTableModel) TabelPlm.getModel();
        List list = new ArrayList<>();
        TabelPlm.setAutoCreateColumnsFromModel(true);
        list.add (TKode.getText());
        list.add (TPekerjaan.getText());
        list.add (TGaji.getText());
        dataModel.addRow(list.toArray());  
       /*
        Pekerjaan pker = new Pekerjaan();
        try {
            pker.setId_Pekerjaan(Idd);
            pker.setSpesialisasi_Pekerjaan(Spl);
           pker.setGaji(Gj);
            
            this.manajemen.insertPkr(pker);
            this.showTableLowongan();
            kosong();
       } catch (SQLException err) {
            System.out.println(err);
        }
       */
    }//GEN-LAST:event_BInsertMouseClicked

    private void BHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHapusMouseClicked

        DefaultTableModel dataModel = (DefaultTableModel) TabelPlm.getModel();
         int j = TabelPlm.getSelectedRow();
         if (j >= 0) {
             
                 
            dataModel.removeRow(j);
            TKode.getText();
            TPekerjaan.getText();
            TGaji.getText();        
          
         }else{ }
                 
    }//GEN-LAST:event_BHapusMouseClicked

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        
          DefaultTableModel Model = (DefaultTableModel) TabelPlm.getModel();
        int i = TabelPlm.getSelectedRow();
        Integer per = Integer.parseInt(Model.getValueAt(i, 0).toString());
        try {
            this.manajemen.deletePkr(per);
            this.showTableLowongan();
        } catch (SQLException ex) {
            Logger.getLogger(Job_Aps.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_BHapusActionPerformed

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1PropertyChange

    private void JBSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSubmitActionPerformed

        dispose();
        try {
            new Job_ApsG().setVisible(true);        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Job_Aps.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBSubmitActionPerformed

    private void TPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPekerjaanActionPerformed

    private void BDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDetailActionPerformed
        // TODO add your handling code here:
        
                                          
       try {
        Manajemen_Lowongan er = this.manajemen.getDataManajemen_Lowongan().get(this.TabelPlm.getSelectedRow());
        String Teks = ("                               -------- DETAIL LOWONGAN --------" + "\n"
                +"\n"
                + "ID_GELOMBANG                                 : " + er.getId_Gelombang().toString()+"\n"
                + "ID_PEKERJAAN                                 : " + er.getPekerjaan().getId_Pekerjaan().toString()+"\n"
                + "SPESIALISASI PEKERJAAN      : " + er.getPekerjaan().getSpesialisasi_Pekerjaan()+"\n"
                + "GAJI                                         : " + er.getPekerjaan().getGaji().toString()+"\n"
                + "TANGGAL                                      : " + er.getTanggal()+"\n"
              
                );
        this.TAreaPLM.setText(Teks);
                } catch (SQLException ex) {
                  System.out.println(ex);
                }
    
    }//GEN-LAST:event_BDetailActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    private void showTableLowongan() throws SQLException {
        DefaultTableModel dtmLowongan = new DefaultTableModel(new String[]
            {"Id Pekerjaan" , "Spesialisasi Pekerjaan" , "Gaji"},0);
        dtmLowongan.setRowCount(0);
        
        for (Pekerjaan p : this.manajemen.getDataPekerjaan()) {
            dtmLowongan.addRow(new String[]
                {p.getId_Pekerjaan().toString() , p.getSpesialisasi_Pekerjaan() ,
                p.getGaji().toString()});
           
            
        }
        
            this.TabelPlm.setModel(dtmLowongan);
    }
    
    
    
    
    private void showTableGl() throws SQLException {
        DefaultTableModel dtmgelo = new DefaultTableModel(new String[]{"Id Gelombang" , "Tanggal" , "Id Pekerjaan"}, 0);
        dtmgelo.setRowCount(0);
        
        for (Manajemen_Lowongan me : this.manajemen.getDataManajemen_Lowongan()) {
          dtmgelo.addRow(new String[]{
                me.getId_Gelombang().toString(),
                me.getTanggal().toString(),
                me.getPekerjaan().getId_Pekerjaan().toString()
            });    
        }
      
            this.Tabelg.setModel(dtmgelo);
    }

  
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Job_Aps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Job_Aps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Job_Aps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Job_Aps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Job_Aps().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Job_Aps.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDetail;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BInsert;
    private javax.swing.JButton BKeluar;
    private javax.swing.JButton BReset;
    private javax.swing.JButton JBSubmit;
    private javax.swing.JLabel LADMIN;
    private javax.swing.JLabel LCari;
    private javax.swing.JLabel LDaftar;
    private javax.swing.JLabel LFungsiPkrjn;
    private javax.swing.JLabel LGaji;
    private javax.swing.JLabel LKode;
    private javax.swing.JTextArea TAreaPLM;
    private javax.swing.JTextField TCari;
    private javax.swing.JTextField TGaji;
    private javax.swing.JTextField TKode;
    private javax.swing.JTextField TPekerjaan;
    private javax.swing.JTable TabelPlm;
    private javax.swing.JTable Tabelg;
    private javax.swing.ButtonGroup bggender;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   
}
