package Admin;

/**
 *
 * @author ade
 */
import Pelamar.FormPelamar;
import project_uas.*;
import Database.Koneksi;
import Job_Aps.Job_Aps;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Masuk
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_kuning = new javax.swing.JPanel();
        Jp_Hitam = new javax.swing.JPanel();
        JB_Pelamar = new javax.swing.JButton();
        JB_Admin = new javax.swing.JButton();
        JL_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Job Applicant Selection System");
        setBackground(new java.awt.Color(51, 153, 255));
        setLocation(new java.awt.Point(620, 220));

        JP_kuning.setBackground(new java.awt.Color(255, 255, 102));

        Jp_Hitam.setBackground(new java.awt.Color(0, 51, 51));

        JB_Pelamar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JB_Pelamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/008-man-with-tie.png"))); // NOI18N
        JB_Pelamar.setText("PELAMAR");
        JB_Pelamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_PelamarActionPerformed(evt);
            }
        });

        JB_Admin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JB_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        JB_Admin.setText("ADMIN");
        JB_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jp_HitamLayout = new javax.swing.GroupLayout(Jp_Hitam);
        Jp_Hitam.setLayout(Jp_HitamLayout);
        Jp_HitamLayout.setHorizontalGroup(
            Jp_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_HitamLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(JB_Pelamar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(JB_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        Jp_HitamLayout.setVerticalGroup(
            Jp_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_HitamLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(Jp_HitamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Pelamar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        JL_login.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JL_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        JL_login.setText("Silahkan Login Sebagai");

        javax.swing.GroupLayout JP_kuningLayout = new javax.swing.GroupLayout(JP_kuning);
        JP_kuning.setLayout(JP_kuningLayout);
        JP_kuningLayout.setHorizontalGroup(
            JP_kuningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_kuningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jp_Hitam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_kuningLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JL_login, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        JP_kuningLayout.setVerticalGroup(
            JP_kuningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_kuningLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(JL_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(Jp_Hitam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_kuning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_kuning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AdminActionPerformed
        // TODO add your handling code here:
       
        dispose();
        new login1().setVisible(true);
        /*try {
            new Job_Aps().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }//GEN-LAST:event_JB_AdminActionPerformed

    private void JB_PelamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_PelamarActionPerformed
        // TODO add your handling code here:
        
         dispose();
         new FormPelamar().setVisible(true);
    }//GEN-LAST:event_JB_PelamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Admin;
    private javax.swing.JButton JB_Pelamar;
    private javax.swing.JLabel JL_login;
    private javax.swing.JPanel JP_kuning;
    private javax.swing.JPanel Jp_Hitam;
    // End of variables declaration//GEN-END:variables
}
